version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/superset-frontend/"
    schedule:
      interval: "daily"
    labels:
      - npm
      - dependabot
    versioning-strategy: increase

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - pip
      - dependabot

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/docs/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/superset-websocket/"
    schedule:
      interval: "daily"
    labels:
      - npm
      - dependabot
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/superset-websocket/utils/client-ws-app/"
    schedule:
      interval: "daily"
    labels:
      - npm
      - dependabot
    versioning-strategy: increase
