table_name: Open Superset Issues
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: main
sql: 'SELECT *, julianday(''now'') - julianday(updated_at) AS days_stale, julianday(''now'')
  - julianday(created_at) AS days_old

  FROM "https://api.github.com/repos/apache/superset/issues"

  WHERE state = ''open''

  ORDER BY updated_at ASC'
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 62f869ed-dc5e-4a2d-b5b3-6ae897ecb385
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: link
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: '''<a href="'' || REPLACE(url, ''https://api.github.com/repos/'', ''https://github.com/'')
    || ''" target="_blank">'' || REPLACE(url, ''https://api.github.com/repos/apache/superset/issues/'',
    ''#'') || ''</a>'' '
  description: null
  python_date_format: null
  extra: {}
- column_name: username
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: json_extract(user,'$.login')
  description: null
  python_date_format: null
  extra: {}
- column_name: days_stale
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: days_old
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: draft
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOL
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: locked
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOL
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: author_association
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: labels_url
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: comments_url
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: node_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: timeline_url
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: pull_request
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: events_url
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: repository_url
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: html_url
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: labels
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: reactions
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: assignees
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: state
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: body
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: title
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: user
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: url
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: number
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: comments
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: created_at
  verbose_name: null
  is_dttm: true
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: updated_at
  verbose_name: null
  is_dttm: true
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: performed_via_github_app
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: active_lock_reason
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: state_reason
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: closed_at
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: assignee
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: milestone
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
version: 1.0.0
database_uuid: fe1710ff-33b3-4542-82ec-005a84cd2f50
