slice_name: Number of Deals (for each Combination)
description: null
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  adhoc_filters: []
  x_axis: deal_size
  groupby: product_line
  bottom_margin: 100
  datasource: 23__table
  granularity_sqla: order_date
  left_margin: 75
  linear_color_scheme: schemePuBuGn
  metric: count
  normalize_across: heatmap_v2
  normalized: true
  queryFields:
    metric: metrics
  row_limit: null
  show_legend: true
  show_percentage: true
  show_values: true
  slice_id: 2810
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  time_range: No filter
  url_params: {}
  viz_type: heatmap_v2
  xscale_interval: null
  value_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  yscale_interval: null
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: bd20fc69-dd51-46c1-99b5-09e37a434bf1
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
