cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  dashboards:
  - 13
  datasource: 22__table
  extra_form_data: {}
  header_font_size: 0.4
  metric: count
  rolling_type: None
  show_trend_line: true
  start_y_axis_at_zero: true
  subheader_font_size: 0.15
  time_format: smart_date
  time_grain_sqla: P1M
  viz_type: big_number
  x_axis: order_date
  y_axis_format: SMART_NUMBER
query_context: null
slice_name: Big Number with Trendline
uuid: 281656a3-3d8d-4423-8b58-b050d59fadd9
version: 1.0.0
viz_type: big_number
