cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  color_scheme: supersetColors
  columns:
  - order_date
  dashboards:
  - 13
  datasource: 22__table
  date_format: smart_date
  extra_form_data: {}
  groupby:
  - product_line
  metrics:
  - count
  number_format: SMART_NUMBER
  temporal_columns_lookup:
    order_date: true
  time_grain_sqla: P1D
  viz_type: box_plot
  whiskerOptions: Tukey
  x_axis_title_margin: 15
  x_ticks_layout: auto
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: null
slice_name: Box Plot
uuid: cc8eea37-f890-4816-8df0-b1354d7cd553
version: 1.0.0
viz_type: box_plot
