cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d638a239-f255-44fc-b0c1-c3f3b7f00ee0
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: start_time
  annotation_layers: []
  color_scheme: supersetAndPresetColors
  dashboards:
  - 9
  datasource: 61__table
  end_time: end_time
  extra_form_data: {}
  legendMargin: 100
  legendOrientation: right
  legendType: plain
  order_by_cols:
  - '["status",false]'
  row_limit: 10000
  series: priority
  show_extra_controls: false
  show_legend: true
  slice_id: 1495
  start_time: start_time
  subcategories: true
  tooltipTimeFormat: smart_date
  tooltipValuesFormat: SMART_NUMBER
  tooltip_columns:
  - project
  - phase
  viz_type: gantt_chart
  x_axis_time_bounds:
  - 08:00:00
  - '19:00:00'
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis: status
  y_axis_title_margin: 50
  zoomable: false
query_context: null
slice_name: Gantt
uuid: c91c242e-ec16-43e4-84fd-1c69336e0a99
version: 1.0.0
viz_type: gantt_chart
