cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  animation: true
  annotation_layers: []
  color_scheme: supersetColors
  dashboards: []
  datasource: 22__table
  end_angle: -45
  extra_form_data: {}
  font_size: 13
  groupby:
  - deal_size
  metric: count
  number_format: SMART_NUMBER
  overlap: true
  round_cap: false
  row_limit: 10
  show_axis_tick: false
  show_pointer: true
  show_progress: true
  show_split_line: false
  split_number: 10
  start_angle: 225
  value_formatter: '{value}'
  viz_type: gauge_chart
query_context: null
slice_name: Gauge
uuid: 57ccf0f1-d28a-4127-9581-7153c5a15b62
version: 1.0.0
viz_type: gauge_chart
