cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  bottom_margin: auto
  dashboards:
  - 13
  datasource: 22__table
  extra_form_data: {}
  groupby: deal_size
  left_margin: auto
  legend_type: continuous
  linear_color_scheme: superset_seq_1
  metric: count
  normalize_across: heatmap
  row_limit: 10000
  show_legend: true
  show_percentage: true
  show_values: true
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  time_grain_sqla: P1D
  value_bounds:
  - null
  - null
  viz_type: heatmap_v2
  x_axis: product_line
  x_axis_time_format: smart_date
  xscale_interval: -1
  y_axis_format: SMART_NUMBER
  yscale_interval: -1
query_context: null
slice_name: Heatmap
uuid: c99dbe37-50da-4067-837c-3a8e5b68aafd
version: 1.0.0
viz_type: heatmap_v2
