cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  bins: 10
  color_scheme: supersetAndPresetColors
  column: quantity_ordered
  dashboards: []
  datasource: 22__table
  extra_form_data: {}
  groupby:
  - deal_size
  normalize: false
  row_limit: 10000
  show_legend: true
  show_value: false
  slice_id: 130
  viz_type: histogram_v2
query_context: null
slice_name: Histogram
uuid: 2a89c19d-d0d2-4f5e-9007-e0fb65440e80
version: 1.0.0
viz_type: histogram_v2
