cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 13
  datasource: 22__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby:
  - product_line
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - count
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  seriesType: echarts_timeseries_line
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1M
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_line
  x_axis: order_date
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: null
slice_name: Line
uuid: 79567e46-97f6-4cd2-8e98-4cd211389743
version: 1.0.0
viz_type: echarts_timeseries_line
