cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  color_scheme: supersetColors
  dashboards: []
  datasource: 22__table
  extra_form_data: {}
  metric: count
  row_limit: 10000
  source: product_line
  target: deal_size
  viz_type: sankey_v2
query_context: null
slice_name: Sankey
uuid: fead4d46-ecb9-4fd9-8b9c-420629269c02
version: 1.0.0
viz_type: sankey_v2
