cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  color_scheme: supersetColors
  columns:
  - year
  - product_line
  dashboards: []
  datasource: 22__table
  date_format: smart_date
  extra_form_data: {}
  label_type: key
  linear_color_scheme: superset_seq_1
  metric: count
  number_format: ~g
  row_limit: 10000
  show_labels: true
  show_labels_threshold: 5
  viz_type: sunburst_v2
query_context: null
slice_name: Sunburst
uuid: 47b26af7-19e0-4ca1-9cf6-b74b2f1f7e3c
version: 1.0.0
viz_type: sunburst_v2
