cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  all_columns:
  - order_date
  - product_line
  - status
  - price_each
  - sales
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  dashboards:
  - 13
  datasource: 22__table
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    order_date: true
  time_grain_sqla: P1D
  viz_type: table
query_context: null
slice_name: Table
uuid: d0e7b367-f16f-4d7a-adde-7c7f455fa9bc
version: 1.0.0
viz_type: table
