cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  color_scheme: supersetColors
  dashboards: []
  datasource: 23__table
  date_format: smart_date
  extra_form_data: {}
  groupby:
  - year
  - product_line
  label_type: key_value
  metric: count
  number_format: SMART_NUMBER
  row_limit: 10000
  show_labels: true
  show_upper_labels: true
  viz_type: treemap_v2
query_context: null
slice_name: TreeMap
uuid: 36367ecc-e09a-4c9f-80df-5dbaf97f741f
version: 1.0.0
viz_type: treemap_v2
