dependencies:
- name: postgresql
  version: 8.1.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: redis
  version: 10.3.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled