---

#------------------------------------------------------------------#
#                       Disclaimer                                 #
#------------------------------------------------------------------#
#    Defining superset_docker_registry. This will be updated in    #
#    /etc/reflex-provisioner/playbooks/superset/main.yml if the    #
#    site_connectivity is offline.                                 #
#------------------------------------------------------------------#
docker_default_registry: "{{ site_default_dck_repo_host }}"

superset_docker_registry: "{{ docker_default_registry }}"

#------------------------------------------------------------------#
#                       Components Version                         #
#------------------------------------------------------------------#
superset_image_tag: "test_12"

#------------------------------------------------------------------#
#                      Docker Path                                 #
#------------------------------------------------------------------#

security_docker_images_root_path: "/opt/repos/security/docker"

#------------------------------------------------------------------#
#                      Docker Images                               #
#------------------------------------------------------------------#

superset_docker_image_name: "{{ superset_docker_registry }}/guavus-superset"

superset_docker_images:
  - name: guavus-superset
    tag: "{{ superset_image_tag }}"

superset_kube_namespace: default

#------------------------------------------------------------------#
#                      Configurations                              #
#------------------------------------------------------------------#

superset_owner_user: 'superset'
superset_owner_password: 'superset'

superset_postgres_access_ip: "{{ platform_loadbalancer_vip_01 }}"
superset_postgres_access_port: "{{ platform_postgresql_port }}"

superset_sql_conn_creds:
  admin:
    postgres:
      user: "{{ platform_postgres_admin_login }}"
      password: "{{ platform_postgres_admin_password }}"

superset_sql_conn_targets:
  postgres:
    host: "{{ superset_postgres_access_ip }}"
    ssl_mode: disable
    engine: postgres

superset_postgres_db: "superset"
superset_postgres_db_user: "{{ superset_sql_conn_creds['admin']['postgres']['user'] }}"
superset_postgres_db_password: "{{ superset_sql_conn_creds['admin']['postgres']['password'] }}"


superset_host_port: "8888"
superset_docker_restart_policy: "Always"

#Path on hosts
superset_host_base_dir: "/opt/guavus/superset"
superset_host_k8s_dir: "{{ superset_host_base_dir }}/deployment/k8s"
superset_host_sql_dir: "{{ superset_host_base_dir }}/deployment/sql"

#------------------------------------------------------------------#
#                      Kerberos Config                               #
#------------------------------------------------------------------#
superset_hive_keytab_name: "hive.service.keytab"
superset_krb5_conf_name: "krb5.conf"

superset_kerberos_config_dir: "{{ superset_host_base_dir }}/krb5-config"

# Config Diretory
superset_config_dir: "{{ role_path }}/../kerberos/files/config"
superset_kerberos_enabled: false


#LDAP configuration
superset_certificate_files: []
SUPERSET_ADMIN_USER_LIST: "" # comma separated userID list 

SUPERSET_AUTH_ROLE_ADMIN: "Admin"
SUPERSET_AUTH_ROLE_PUBLIC: "Public"

SUPERSET_AUTH_TYPE: "AUTH_DB"
SUPERSET_AUTH_USER_REGISTRATION: True
SUPERSET_AUTH_USER_REGISTRATION_ROLE: "Dashboard_Viewer"
SUPERSET_AUTH_LDAP_USE_TLS: False
SUPERSET_AUTH_LDAP_SERVER: "" # ldap://guavus.com:389 (Define the DN for the user that will be used for the initial LDAP BIND. This is necessary for OpenLDAP and can be used on MSFT AD.)
SUPERSET_AUTH_LDAP_BIND_USER: "" # cn=Ankur Singhal,ou=gurgaon,ou=India,ou=UserIDs,dc=guavus,dc=com
SUPERSET_AUTH_LDAP_BIND_PASSWORD: "" # Define password for the bind user.

SUPERSET_AUTH_LDAP_TLS_DEMAND: False
SUPERSET_AUTH_LDAP_TLS_CACERTDIR: "/etc/cert/"
SUPERSET_AUTH_LDAP_TLS_CACERTFILE: ""
SUPERSET_AUTH_LDAP_TLS_CERTFILE: ""
SUPERSET_AUTH_LDAP_TLS_KEYFILE: ""

SUPERSET_AUTH_LDAP_SEARCH: "" #dc=guavus,dc=com
SUPERSET_AUTH_LDAP_UID_FIELD: "uid" #sAMAccountName
SUPERSET_AUTH_LDAP_FIRSTNAME_FIELD: "givenName"
SUPERSET_AUTH_LDAP_LASTNAME_FIELD: "sn"
SUPERSET_AUTH_LDAP_EMAIL_FIELD: "mail"
SUPERSET_AUTH_LDAP_ALLOW_SELF_SIGNED: False
SUPERSET_AUTH_LDAP_APPEND_DOMAIN: ""
SUPERSET_AUTH_LDAP_USERNAME_FORMAT: ""
SUPERSET_AUTH_LDAP_SEARCH_FILTER: ""
RVF_APP_NAME: "Dashboard Builder"
SUPERSET_SESSION_LIFETIME_SECONDS: "3600" # stale session timeout
