{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}-postgresql
  labels:
    {{- include "superset.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
