{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "superset.fullname" . }}-postgresql
  labels:
    {{- include "superset.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "superset.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
