table_name: channels
main_dttm_col: created
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: null
params: null
template_params: null
filter_select_enabled: false
fetch_values_predicate: null
extra: null
uuid: f7db6d45-7056-f395-d24a-6c805fb4c97d
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  extra: null
  warning_text: null
columns:
- column_name: topic__last_set
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: purpose__last_set
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: created
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: unlinked
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: topic__creator
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: purpose__creator
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: topic__value
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: purpose__value
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: parent_conversation
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: name_normalized
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: channel_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: creator
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_pending_ext_shared
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_ext_shared
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_org_shared
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_archived
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_channel
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_shared
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_general
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_private
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_member
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_group
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_mpim
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_im
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: num_members
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: pending_connected_team_ids
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: shared_team_ids
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: pending_shared
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: previous_names
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: members
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
version: 1.0.0
database_uuid: a2dc77af-e654-49bb-b321-40f6b559a1ee
data: https://raw.githubusercontent.com/apache-superset/examples-data/master/datasets/examples/slack/channels.csv
