# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
table_name: messages
main_dttm_col: bot_profile__updated
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
uuid: e032c69e-716e-d700-eff7-07800d0f9989
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  extra: null
  warning_text: null
columns:
- column_name: bot_profile__updated
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: last_read
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: ts
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: bot_profile__team_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: bot_profile__app_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: bot_profile__name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: bot_profile__id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: parent_user_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: client_msg_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: icons__emoji
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: channel_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: source_team
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: thread_ts
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: old_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: latest_reply
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: user_team
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: bot_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: file_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: username
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: permalink
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: team
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: subtype
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: topic
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: inviter
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: purpose
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: type
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: user
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: text
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: bot_profile__deleted
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: display_as_bot
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_delayed_message
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_starred
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_intro
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: upload
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: subscribed
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: reply_users_count
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: unread_count
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: reply_count
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: file_ids
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: pinned_to
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: reply_users
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: reactions
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: blocks
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
version: 1.0.0
database_uuid: a2dc77af-e654-49bb-b321-40f6b559a1ee
data: https://raw.githubusercontent.com/apache-superset/examples-data/master/datasets/examples/slack/messages.csv
