# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
table_name: users
main_dttm_col: updated
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
uuid: 7195db6b-2d17-7619-b7c7-26b15378df8c
metrics:
  - metric_name: count
    verbose_name: COUNT(*)
    metric_type: count
    expression: COUNT(*)
    description: null
    d3format: null
    extra: null
    warning_text: null
columns:
  - column_name: updated
    verbose_name: null
    is_dttm: true
    is_active: true
    type: TIMESTAMP WITHOUT TIME ZONE
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: has_2fa
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: real_name
    verbose_name: null
    is_dttm: false
    is_active: true
    type: VARCHAR
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: tz_label
    verbose_name: null
    is_dttm: false
    is_active: true
    type: VARCHAR
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: team_id
    verbose_name: null
    is_dttm: false
    is_active: true
    type: VARCHAR
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: name
    verbose_name: null
    is_dttm: false
    is_active: true
    type: VARCHAR
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: color
    verbose_name: null
    is_dttm: false
    is_active: true
    type: VARCHAR
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: id
    verbose_name: null
    is_dttm: false
    is_active: true
    type: VARCHAR
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: tz
    verbose_name: null
    is_dttm: false
    is_active: true
    type: VARCHAR
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: is_ultra_restricted
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: is_primary_owner
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: is_app_user
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: is_admin
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: is_bot
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: is_restricted
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: is_owner
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: deleted
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BOOLEAN
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
  - column_name: tz_offset
    verbose_name: null
    is_dttm: false
    is_active: true
    type: BIGINT
    groupby: true
    filterable: true
    expression: null
    description: null
    python_date_format: null
version: 1.0.0
database_uuid: a2dc77af-e654-49bb-b321-40f6b559a1ee
data: https://raw.githubusercontent.com/apache-superset/examples-data/master/datasets/examples/slack/users.csv
