cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 0a42e7e4-2420-4f41-8612-fb041f2f46a9
description: null
params:
  entity: DEPT_ID
  granularity_sqla: ''
  metric:
    aggregate: AVG
    column:
      column_name: '2004'
      type: INT
    expressionType: SIMPLE
    label: Boys
    optionName: metric_112342
  row_limit: 500000
  select_country: france
  since: ''
  until: ''
  viz_type: country_map
query_context: null
slice_name: Birth in France by department in 2016
uuid: b1286583-f6cb-4956-ba3a-a3a7fbe8d47e
version: 1.0.0
viz_type: country_map
