trigger:
  batch: true
  branches:
    include:
      - cccs-*

variables:
  containerRegistry: uchimera
  imageRepository: cccs/superset-base
  dockerfile: $(Build.SourcesDirectory)/Dockerfile
  npmrc: $(Build.SourcesDirectory)/superset-frontend/.npmrc
  buildTimestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  DOCKER_BUILDKIT: 1

pool: cauldron-vmss

steps:
  - bash: |
      BRANCH_NAME=$(echo "$SYSTEM_PULLREQUEST_SOURCEBRANCH $BUILD_SOURCEBRANCH" | sed -r 's/^\s*(refs\/heads\/)?(\S*).*$/\2/' | sed 's/\//_/g')
      echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
    displayName: Parse Source Control Branch Name
  - task: npmAuthenticate@0
    inputs:
      workingFile: $(npmrc)
    displayName: Authenticate to npm feed
  - task: Docker@2
    displayName: Login to $(containerRegistry)
    inputs:
      command: login
      containerRegistry: $(containerRegistry)
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      repository: $(imageRepository)
      arguments: --progress=plain
      dockerfile: $(dockerfile)
      tags: |
        $(BRANCH_NAME)
        $(BRANCH_NAME)_$(buildTimestamp)_b$(Build.BuildId)
  - task: Docker@2
    displayName: Push image
    inputs:
      command: push
      repository: $(imageRepository)
      tags: |
        $(BRANCH_NAME)
        $(BRANCH_NAME)_$(buildTimestamp)_b$(Build.BuildId)
