{{- if and .Values.redis.enabled .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}-redis
  labels:
    {{- include "superset.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
