cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f1dc524d-a988-47f5-8860-9419410cc68c
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '100'
  markup_type: markdown
  metric: sum__num
  rotation: square
  row_limit: 50000
  series: name
  size_from: '10'
  size_to: '70'
  time_range: '100 years ago : now'
  viz_type: word_cloud
query_context: null
slice_name: Boy Name Cloud
uuid: eae9452d-6432-40fa-82b1-9a3944120d9b
version: 1.0.0
viz_type: word_cloud
