cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f1dc524d-a988-47f5-8860-9419410cc68c
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50
  time_range: '100 years ago : now'
  timeseries_limit_metric: sum__num
  viz_type: table
query_context: null
slice_name: Boys
uuid: 4c7484f2-3c8a-4328-ad91-55f6366035bf
version: 1.0.0
viz_type: table
