cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f1dc524d-a988-47f5-8860-9419410cc68c
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - gender
  limit: '25'
  markup_type: markdown
  metric: sum__num
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: pie
query_context: null
slice_name: Genders
uuid: 4952e06b-7a81-43e4-a7b8-8ebaf2473bf0
version: 1.0.0
viz_type: pie
