cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f1dc524d-a988-47f5-8860-9419410cc68c
description: null
params:
  compare_lag: '5'
  compare_suffix: over 5Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__num
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: big_number
query_context: null
slice_name: Participants
uuid: 3817bbd9-bb9c-4310-afa0-249b742da773
version: 1.0.0
viz_type: big_number
