# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f1dc524d-a988-47f5-8860-9419410cc68c
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  comparison_type: values
  granularity_sqla: ds
  groupby:
  - name
  limit: 10
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  stacked_style: expand
  time_grain_sqla: P1D
  time_range: '100 years ago : now'
  viz_type: echarts_area
  x_axis_forma: smart_date
query_context: null
slice_name: Top 10 Girl Name Share
uuid: 28f36cf3-2ab9-47a4-b324-c3bc084fb0d4
version: 1.0.0
viz_type: echarts_area
