cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f1dc524d-a988-47f5-8860-9419410cc68c
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  comparison_type: values
  granularity_sqla: ds
  groupby:
  - name
  limit: 10
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  stacked_style: expand
  time_grain_sqla: P1D
  time_range: '100 years ago : now'
  viz_type: echarts_area
  x_axis_forma: smart_date
query_context: null
slice_name: Top 10 Girl Name Share
uuid: 28f36cf3-2ab9-47a4-b324-c3bc084fb0d4
version: 1.0.0
viz_type: echarts_area
