cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 69935018-2dcf-489a-8147-83e68926c88d
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: table
query_context: null
slice_name: Most Populated Countries
uuid: 4794cf92-ae2f-40e0-aab3-ac2b32d25890
version: 1.0.0
viz_type: table
