cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 69935018-2dcf-489a-8147-83e68926c88d
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_RUR_TOTL_ZS
  num_period_compare: '10'
  row_limit: 50000
  secondary_metric:
    aggregate: SUM
    column:
      column_name: SP_RUR_TOTL
      optionName: _col_SP_RUR_TOTL
      type: DOUBLE
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Rural Population
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: world_map
query_context: null
slice_name: '% Rural'
uuid: 91ca6ea2-4a08-4633-b98f-7b48f448af52
version: 1.0.0
viz_type: world_map
