slice_name: Genders by State
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - other
    expressionType: SIMPLE
    filterOptionName: 2745eae5
    operator: NOT IN
    subject: state
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - state
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num_boys
      type: BIGINT(20)
    expressionType: SIMPLE
    label: Boys
    optionName: metric_11
  - aggregate: SUM
    column:
      column_name: num_girls
      type: BIGINT(20)
    expressionType: SIMPLE
    label: Girls
    optionName: metric_12
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: echarts_timeseries_bar
query_context: null
cache_timeout: null
uuid: c4c52e3d-63ac-48ac-b064-7a6f3c5a7705
version: 1.0.0
dataset_uuid: 3758a086-e040-490e-8ac3-530633f7ce51
