slice_name: Genders
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - gender
  limit: '25'
  markup_type: markdown
  metric: sum__num
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: pie
query_context: null
cache_timeout: null
uuid: 62376a53-3e0f-4ba9-b3ea-dfa7169951da
version: 1.0.0
dataset_uuid: 3758a086-e040-490e-8ac3-530633f7ce51
