slice_name: Girl Name Cloud
description: null
certified_by: null
certification_details: null
viz_type: word_cloud
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '100'
  markup_type: markdown
  metric: sum__num
  rotation: square
  row_limit: 50000
  series: name
  size_from: '10'
  size_to: '70'
  time_range: '100 years ago : now'
  viz_type: word_cloud
query_context: null
cache_timeout: null
uuid: 736b1a84-1af5-41c7-a159-36492fa9666e
version: 1.0.0
dataset_uuid: 3758a086-e040-490e-8ac3-530633f7ce51
