slice_name: Girls
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50
  time_range: '100 years ago : now'
  timeseries_limit_metric: sum__num
  viz_type: table
query_context: null
cache_timeout: null
uuid: afa751f8-9a35-4bdc-9192-453ca1fce662
version: 1.0.0
dataset_uuid: 3758a086-e040-490e-8ac3-530633f7ce51
