cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 0fa46739-64ec-45ea-adb3-ae690c2007a0
description: null
params:
  autozoom: false
  color_picker:
    a: 1
    b: 0
    g: 255
    r: 14
  datasource: 5__table
  extruded: true
  granularity_sqla: null
  grid_size: 120
  groupby: []
  mapbox_style: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  point_radius: Auto
  point_radius_fixed:
    type: fix
    value: 2000
  point_radius_unit: Pixels
  row_limit: 5000
  size: count
  spatial:
    latCol: LAT
    lonCol: LON
    type: latlong
  time_grain_sqla: null
  time_range: No filter
  viewport:
    bearing: 155.80099696026355
    latitude: 37.7942314882596
    longitude: -122.42066918995666
    pitch: 53.470800300695146
    zoom: 12.699690845482069
  viz_type: deck_grid
query_context: null
slice_name: Deck.gl Grid
uuid: b3cf1dbd-2b70-4db6-8a71-ae973cfadc39
version: 1.0.0
viz_type: deck_grid
