cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e4bb97f4-4686-4476-8297-48583f0361a3
description: null
params:
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  datasource: 10__table
  end_spatial:
    latCol: LATITUDE_DEST
    lonCol: LONGITUDE_DEST
    type: latlong
  granularity_sqla: null
  mapbox_style: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  row_limit: 5000
  slice_id: 42
  start_spatial:
    latCol: LATITUDE
    lonCol: LONGITUDE
    type: latlong
  stroke_width: 1
  time_grain_sqla: null
  time_range: ' : '
  viewport:
    altitude: 1.5
    bearing: 8.546256357301871
    height: 642
    latitude: 44.596651438714254
    longitude: -91.84340711201104
    maxLatitude: 85.05113
    maxPitch: 60
    maxZoom: 20
    minLatitude: -85.05113
    minPitch: 0
    minZoom: 0
    pitch: 60
    width: 997
    zoom: 2.929837070560775
  viz_type: deck_arc
query_context: null
slice_name: Deck.gl Arcs
uuid: f10e6064-9b20-45f2-9411-97aac5a53e59
version: 1.0.0
viz_type: deck_arc
