cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 0fa46739-64ec-45ea-adb3-ae690c2007a0
description: null
params:
  color_picker:
    a: 1
    b: 0
    g: 255
    r: 14
  datasource: 5__table
  granularity_sqla: null
  grid_size: 20
  groupby: []
  mapbox_style: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  point_radius: Auto
  point_radius_fixed:
    type: fix
    value: 2000
  point_unit: square_m
  row_limit: 5000
  size: count
  spatial:
    latCol: LAT
    lonCol: LON
    type: latlong
  time_grain_sqla: null
  time_range: No filter
  viewport:
    bearing: -4.952916738791771
    latitude: 37.76024135844065
    longitude: -122.41827069521386
    pitch: 4.750411100577438
    zoom: 14.161641703941438
  viz_type: deck_screengrid
query_context: null
slice_name: Deck.gl Screen grid
uuid: 76d8bcca-c27e-440e-9601-337c86642709
version: 1.0.0
viz_type: deck_screengrid
