cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  column: age
  datasource: 42__table
  groupby: []
  label_colors: {}
  link_length: '25'
  row_limit: 10000
  slice_id: 1380
  url_params: {}
  viz_type: histogram_v2
  x_axis_title: age
  y_axis_title: count
query_context: null
slice_name: Age distribution of respondents
uuid: 5f1ea868-604e-f69d-a241-5daa83ff33be
version: 1.0.0
viz_type: histogram_v2
