cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  country_fieldtype: name
  datasource: 42__table
  entity: country_citizen
  granularity_sqla: time_start
  linear_color_scheme: preset_div_1
  max_bubble_size: '25'
  metric: count
  queryFields:
    entity: groupby
    metric: metrics
    secondary_metric: metrics
  row_limit: null
  secondary_metric:
    aggregate: COUNT
    column:
      column_name: country_live
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1570
      is_dttm: false
      python_date_format: null
      type: TEXT
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT(country_live)
    optionName: metric_azxwoyei39f_d7xgzshjnw6
    sqlExpression: null
  show_bubbles: true
  slice_id: 1388
  time_range: No filter
  url_params: {}
  viz_type: world_map
query_context: null
slice_name: Country of Citizenship
uuid: 2ba66056-a756-d6a3-aaec-0c243fb7062e
version: 1.0.0
viz_type: world_map
