cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: Currently A Developer
    expressionType: SIMPLE
    filterOptionName: filter_fvi0jg9aii_2lekqrhy7qk
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: developer_type
  - clause: WHERE
    comparator: '100000'
    expressionType: SIMPLE
    filterOptionName: filter_khdc3iypzjg_3g6h02b4f2p
    isExtra: false
    isNew: false
    operator: <=
    sqlExpression: null
    subject: last_yr_income
  annotation_layers: []
  color_scheme: supersetColors
  column: last_yr_income
  datasource: 42__table
  groupby: []
  label_colors: {}
  link_length: '10'
  row_limit: null
  url_params: {}
  viz_type: histogram_v2
query_context: null
slice_name: Last Year Income Distribution
uuid: a2ec5256-94b4-43c4-b8c7-b83f70c5d4df
version: 1.0.0
viz_type: histogram_v2
