cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_yccan09xctb_wjwt23qhknf
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: is_software_dev
  annotation_layers: []
  color_scheme: supersetColors
  datasource: 42__table
  donut: true
  granularity_sqla: time_start
  groupby:
  - willing_to_relocate
  innerRadius: 44
  label_type: key
  labels_outside: true
  metric: count
  number_format: SMART_NUMBER
  outerRadius: 69
  queryFields:
    groupby: groupby
    metric: metrics
  row_limit: null
  show_labels: true
  show_legend: false
  slice_id: 1365
  time_range: No filter
  url_params: {}
  viz_type: pie
query_context: null
slice_name: ✈️ Relocation ability
uuid: a6dd2d5a-2cdc-c8ec-f30c-85920f4f8a65
version: 1.0.0
viz_type: pie
