cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: 'NULL'
    expressionType: SIMPLE
    filterOptionName: filter_ameaka2efjv_rfv1et5nwng
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: lang_at_home
  all_columns: []
  annotation_layers: []
  color_pn: true
  datasource: 42__table
  granularity_sqla: time_start
  groupby:
  - lang_at_home
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: aggregate
  row_limit: '15'
  show_cell_bars: true
  slice_id: 1386
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: table
query_context: null
slice_name: Top 15 Languages Spoken at Home
uuid: 03a74c97-52fc-cf87-233c-d4275f8c550c
version: 1.0.0
viz_type: table
