slice_name: Rural Breakdown
description: null
certified_by: null
certification_details: null
viz_type: sunburst_v2
params:
  columns:
  - region
  - country_name
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  secondary_metric:
    aggregate: SUM
    column:
      column_name: SP_RUR_TOTL
      optionName: _col_SP_RUR_TOTL
      type: DOUBLE
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Rural Population
  show_bubbles: true
  since: '2011-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2011-01-02'
  viz_type: sunburst_v2
query_context: null
cache_timeout: null
uuid: a4b90192-b6be-4d11-871c-d3f17aa8a63a
version: 1.0.0
dataset_uuid: 41156372-3528-4550-b40c-93a170d4cbf7
