slice_name: Treemap
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  - country_code
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: treemap_v2
query_context: null
cache_timeout: null
uuid: f069cea2-404c-42df-b707-c9fd9fa55bf1
version: 1.0.0
dataset_uuid: 41156372-3528-4550-b40c-93a170d4cbf7
