slice_name: World's Population
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  compare_lag: '10'
  compare_suffix: over 10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2000'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: big_number
query_context: null
cache_timeout: null
uuid: 9eb0e3e2-3b6f-4a96-acbb-1ff4e5b751cd
version: 1.0.0
dataset_uuid: 41156372-3528-4550-b40c-93a170d4cbf7
