name: License Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  check-secrets:
    uses: ./.github/workflows/check-secrets.yml
    with:
      secret_name: 'FOSSA_API_KEY'
    secrets: inherit
  license_check:
    needs: check-secrets
    if: needs.check-secrets.outputs.has-secrets == '1'
    name: License Check
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Generate fossa report
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          set -eo pipefail
          if [[ "${{github.event_name}}" != "pull_request" ]]; then
            ./scripts/fossa.sh
            exit 0
          fi

          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')

          cat<<EOF
          CHANGED FILES:
          $FILES

          EOF

          if [[ "${FILES}" =~ (.*package*\.json|requirements\/[a-z_-]+\.txt|setup\.py) ]]; then
            echo "Detected dependency changes... running fossa check"

            ./scripts/fossa.sh
          else
            echo "No dependency changes... skiping fossa check"
          fi
        shell: bash
      - name: Run license check
        run: ./scripts/check_license.sh
