name: Upload Technical Debt Metrics to Google Sheets

on:
  push:
    branches:
      - master
      - "[0-9].[0-9]*"

jobs:
  config:
    runs-on: ubuntu-24.04
    outputs:
      has-secrets: ${{ steps.check.outputs.has-secrets }}
    steps:
      - name: "Check for secrets"
        id: check
        shell: bash
        run: |
          if [ -n "${{ (secrets.GSHEET_KEY != '' ) || '' }}" ]; then
            echo "has-secrets=1" >> "$GITHUB_OUTPUT"
          fi

  process-and-upload:
    needs: config
    if: needs.config.outputs.has-secrets
    runs-on: ubuntu-24.04
    name: Generate Reports
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile
        working-directory: ./superset-frontend

      - name: Run Script
        env:
          SPREADSHEET_ID: "1oABNnzxJYzwUrHjr_c9wfYEq9dFL1ScVof9LlaAdxvo"
          SERVICE_ACCOUNT_KEY: ${{ secrets.GSHEET_KEY }}
        run: bun run lint-stats
        continue-on-error: true
        working-directory: ./superset-frontend
