slice_name: Birth in France by department in 2016
description: null
certified_by: null
certification_details: null
viz_type: country_map
params:
  entity: DEPT_ID
  granularity_sqla: ''
  metric:
    aggregate: AVG
    column:
      column_name: '2004'
      type: INT
    expressionType: SIMPLE
    label: Boys
    optionName: metric_112342
  row_limit: 500000
  select_country: france
  since: ''
  until: ''
  viz_type: country_map
query_context: null
cache_timeout: null
uuid: 26b3bbd2-4a6e-4b1d-8a52-4aca217bbd3d
version: 1.0.0
dataset_uuid: d1801260-332a-4c9d-ae50-c23a432a7ac6
